// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIf_2KQyI66nASeqNeSgiCV-H0lxAIcGU',
    appId: '1:463558689271:web:438a4194d0e52d6c366ef2',
    messagingSenderId: '463558689271',
    projectId: 'virtual-run-7b75d',
    authDomain: 'virtual-run-7b75d.firebaseapp.com',
    storageBucket: 'virtual-run-7b75d.appspot.com',
    measurementId: 'G-E0VCZBKVD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaAH9ODNfMG5uMREvVPjn6Hc63YQqbO2A',
    appId: '1:463558689271:android:3a6eb5b12d91bad3366ef2',
    messagingSenderId: '463558689271',
    projectId: 'virtual-run-7b75d',
    storageBucket: 'virtual-run-7b75d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvgKx5M0yA1m9isEivjNhomNPgDSQSw9g',
    appId: '1:463558689271:ios:9582d5bfa6d1f9a9366ef2',
    messagingSenderId: '463558689271',
    projectId: 'virtual-run-7b75d',
    storageBucket: 'virtual-run-7b75d.appspot.com',
    androidClientId: '463558689271-a83mrv6d692o3ghg60vp50abt5c6125e.apps.googleusercontent.com',
    iosClientId: '463558689271-af9vhub56lnu1dfarn85mbcmed2g5mjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.wetalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvgKx5M0yA1m9isEivjNhomNPgDSQSw9g',
    appId: '1:463558689271:ios:9e6e4553a7f1e6d3366ef2',
    messagingSenderId: '463558689271',
    projectId: 'virtual-run-7b75d',
    storageBucket: 'virtual-run-7b75d.appspot.com',
    androidClientId: '463558689271-a83mrv6d692o3ghg60vp50abt5c6125e.apps.googleusercontent.com',
    iosClientId: '463558689271-n5g2cb1jde7vcm6ssd10s4k5d2v1c1ed.apps.googleusercontent.com',
    iosBundleId: 'com.example.wetalk.RunnerTests',
  );
}
